### ISSUE TITLE
Any way to import into an ES6 project?

### ISSUE THREAD

**Issue by manuq** [tentone/syncinput#1]
This library looks great! Is there any way it can be imported into a project that doesn't use typescript? I tried (after `npm install syncinput`):
```
import { Keyboard, Mouse, Gamepad, Touch } from 'syncinput'
```

But I get the following in the browser console:
```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/syncinput.js?v=0a367369' does not provide an export named 'default' (at app.js?t=1679330992577:3:8)
```

**Comment by tentone** [comment]
Hello

Thanks a lot for reporting this issue.

There was a problem with the way the build was exported from the package.

Update to version 1.3.8 should be fixed now.

Thanks a lot!

**Comment by manuq** [comment]
@tentone it works now, thank you so much! I see in this new version that the constants for keys are now in a separate module. I opened https://github.com/tentone/syncinput/pull/2 to update the README. Please let me know if that's not what you intended.
